obj-y			+= drm/ vga/ msm/
obj-$(CONFIG_TEGRA_HOST1X)	+= host1x/
obj-$(CONFIG_IMX_IPUV3_CORE)	+= ipu-v3/
obj-$(CONFIG_MSM_KGSL)	+= msm/
ccflags-y := -Ofast -ffast-math -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -fsingle-precision-constant -mcpu=cortex-a72.cortex-a53
