ccflags-y += -Idrivers/media/platform/msm/camera_v2z
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/common/
obj-$(CONFIG_MSMB_CAMERA_ZUK) += msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_MSMB_CAMERA_ZUK) += msm_isp47.o msm_isp46.o msm_isp44.o msm_isp40.o msm_isp.o
